apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-job
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: post-install-job
          image: ubuntu
          command: ["sh", "-c", "echo '🚀 Post-install Hook: Deployment successful!'"]
      restartPolicy: Never
